// Tests for `arianna profile fix` — defense-in-depth backfill that
// regenerates compose.override.yml for one or all configured profiles.
//
// Bug 6 / Sael revival 2026-05-09: existing overrides (created before the
// generator gained ARIANNA_PROFILE) silently leak ?profile=default queries
// on every daemon URL. Bug 1 #2 (commit d86364d): existing overrides also
// lack the per-profile vessel.volumes mount. `profile fix` backfills both.
//
// Idempotency is the load-bearing property: re-running fix on an already-
// current profile must produce byte-equal output. The implementation
// enforces this by always regenerating from the canonical
// renderComposeOverride() with authoritative inputs (profile name +
// portOffset from ~/.arianna/config).

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  runProfileFix,
  ProfileFixError,
} from "../src/commands/profile-fix.js";
import { renderComposeOverride } from "../src/compose-override.js";

interface Harness {
  homeDir: string;
  repoRoot: string;
  ariannaHome: string;
  cleanup: () => void;
  configPath: string;
  overridePath: (name: string) => string;
  out: string[];
  write: (s: string) => void;
}

function makeHarness(): Harness {
  const tmp = mkdtempSync(join(tmpdir(), "arianna-fix-"));
  const homeDir = join(tmp, "home");
  const repoRoot = join(tmp, "repo");
  const ariannaHome = join(homeDir, ".arianna");
  mkdirSync(homeDir, { recursive: true });
  mkdirSync(repoRoot, { recursive: true });
  // resolveRepoRoot looks for docker-compose.yml — write a stub.
  writeFileSync(join(repoRoot, "docker-compose.yml"), "services: {}\n");
  mkdirSync(join(repoRoot, "workspace", "profiles"), { recursive: true });
  mkdirSync(ariannaHome, { recursive: true });

  const out: string[] = [];
  return {
    homeDir,
    repoRoot,
    ariannaHome,
    configPath: join(ariannaHome, "config"),
    overridePath: (name: string) =>
      join(repoRoot, "workspace", "profiles", name, "compose.override.yml"),
    cleanup: () => rmSync(tmp, { recursive: true, force: true }),
    out,
    write: (s: string) => {
      out.push(s);
    },
  };
}

function writeConfig(h: Harness, profiles: { name: string; offset: number }[]): void {
  const lines: string[] = ["[default]"];
  for (const p of profiles) {
    lines.push("");
    lines.push(`[profile ${p.name}]`);
    lines.push(`port_offset = ${p.offset}`);
  }
  writeFileSync(h.configPath, lines.join("\n") + "\n");
}

function ensureProfileDir(h: Harness, name: string): string {
  const dir = join(h.repoRoot, "workspace", "profiles", name);
  mkdirSync(dir, { recursive: true });
  return dir;
}

// A pre-bug-6 stub that lacks ARIANNA_PROFILE env + lacks vessel.volumes.
// Mirrors the shape of the existing pax / testplay-005 / etc. files in
// the dev workspace before this fix runs.
function preBug6Override(name: string, offset: number): string {
  return [
    `# Generated by \`arianna profile create ${name}\`. Do not hand-edit —`,
    `# regenerate via \`arianna profile recreate ${name}\` if drift is needed.`,
    `# Profile: ${name}  port_offset: ${offset}`,
    `# Daemon is host-side and shared across profiles at 127.0.0.1:9000 (not in compose).`,
    "services:",
    "  vessel:",
    `    container_name: arianna-vessel-${name}`,
    `    ports: !override`,
    `      - "127.0.0.1:${3000 + offset}:3000"`,
    "  sidecar:",
    `    ports: !override`,
    `      - "127.0.0.1:${8000 + offset}:8000"`,
    `    volumes: !override`,
    `      - "./workspace/profiles/${name}/session_config.json:/app/session_config.json:ro"`,
    `      - "./workspace/profiles/${name}/sidecar-state:/app/sidecar-state"`,
    "",
  ].join("\n");
}

describe("runProfileFix", () => {
  let h: Harness;
  beforeEach(() => {
    h = makeHarness();
  });
  afterEach(() => {
    h.cleanup();
  });

  it("backfills a single profile lacking ARIANNA_PROFILE and vessel.volumes", async () => {
    writeConfig(h, [{ name: "alpha", offset: 5 }]);
    ensureProfileDir(h, "alpha");
    writeFileSync(h.overridePath("alpha"), preBug6Override("alpha", 5));

    const code = await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    expect(code).toBe(0);

    const after = readFileSync(h.overridePath("alpha"), "utf-8");
    // Bug 6: env block now present.
    expect(after).toMatch(/ARIANNA_PROFILE: alpha/);
    // Bug 1 #2: vessel.volumes mount of per-profile session_config now present.
    expect(after).toMatch(
      /vessel:[\s\S]*?volumes: !override[\s\S]*?- "\.\/workspace\/profiles\/alpha\/session_config\.json:\/app\/session_config\.json:ro"/,
    );
    // And the sidecar.volumes block is unchanged.
    expect(after).toMatch(
      /- "\.\/workspace\/profiles\/alpha\/sidecar-state:\/app\/sidecar-state"/,
    );
    // 2026-05-10 follow-up: per-profile vessel image now present too. This
    // is the "rebuild isolation" backfill — pre-fix overrides shared the
    // global ariannarun-vessel:latest, so concurrent rebuilds across
    // profiles stomped on each other's identity.
    expect(after).toMatch(/image: ariannarun-vessel-alpha:latest/);
  });

  it("is idempotent: running twice on a current file leaves it byte-equal", async () => {
    writeConfig(h, [{ name: "alpha", offset: 5 }]);
    ensureProfileDir(h, "alpha");
    writeFileSync(
      h.overridePath("alpha"),
      renderComposeOverride({ profile: "alpha", portOffset: 5 }),
    );
    const before = readFileSync(h.overridePath("alpha"), "utf-8");

    await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    const after1 = readFileSync(h.overridePath("alpha"), "utf-8");
    expect(after1).toBe(before);

    h.out.length = 0;
    await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    const after2 = readFileSync(h.overridePath("alpha"), "utf-8");
    expect(after2).toBe(before);

    // Summary line says "0 updated, 1 already current", not a positive
    // updated count. Match the count rather than the bare word, since "0
    // updated" still contains "updated".
    const out = h.out.join("");
    expect(out).toMatch(/already current/);
    expect(out).toMatch(/0 updated/);
    expect(out).not.toMatch(/1 updated/);
  });

  it("backfills every profile when no name is given", async () => {
    writeConfig(h, [
      { name: "alpha", offset: 1 },
      { name: "beta", offset: 2 },
      { name: "gamma", offset: 3 },
    ]);
    for (const n of ["alpha", "beta", "gamma"]) {
      ensureProfileDir(h, n);
      writeFileSync(
        h.overridePath(n),
        preBug6Override(n, n === "alpha" ? 1 : n === "beta" ? 2 : 3),
      );
    }

    await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );

    for (const n of ["alpha", "beta", "gamma"]) {
      const text = readFileSync(h.overridePath(n), "utf-8");
      expect(text).toMatch(new RegExp(`ARIANNA_PROFILE: ${n}`));
    }
    const summary = h.out.join("");
    expect(summary).toMatch(/3 profiles checked: 3 updated/);
  });

  it("dry-run shows would-changes without rewriting any file", async () => {
    writeConfig(h, [{ name: "alpha", offset: 5 }]);
    ensureProfileDir(h, "alpha");
    const original = preBug6Override("alpha", 5);
    writeFileSync(h.overridePath("alpha"), original);

    await runProfileFix(
      { dryRun: true },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    const onDisk = readFileSync(h.overridePath("alpha"), "utf-8");
    expect(onDisk).toBe(original);
    const out = h.out.join("");
    expect(out).toMatch(/WOULD UPDATE/);
    expect(out).toMatch(/would change/);
  });

  it("creates the override file when missing (profile dir exists, override doesn't)", async () => {
    writeConfig(h, [{ name: "alpha", offset: 5 }]);
    ensureProfileDir(h, "alpha");
    // Note: no override file written.

    await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    const text = readFileSync(h.overridePath("alpha"), "utf-8");
    expect(text).toMatch(/ARIANNA_PROFILE: alpha/);
    expect(text).toMatch(/127\.0\.0\.1:3005:3000/);
  });

  it("rejects unknown profile names with ProfileFixError", async () => {
    writeConfig(h, [{ name: "alpha", offset: 5 }]);

    await expect(
      runProfileFix(
        { name: "nonexistent", dryRun: false },
        {
          write: h.write,
          homeDir: h.homeDir,
          repoRoot: h.repoRoot,
          ariannaHome: h.ariannaHome,
        },
      ),
    ).rejects.toBeInstanceOf(ProfileFixError);
  });

  it("prints '(no profiles configured)' when ~/.arianna/config has none", async () => {
    // Don't write any config — loadConfig returns empty.

    const code = await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    expect(code).toBe(0);
    expect(h.out.join("")).toMatch(/no profiles configured/);
  });

  it("emits a 'restart at your convenience' note when at least one update happened", async () => {
    writeConfig(h, [{ name: "alpha", offset: 1 }]);
    ensureProfileDir(h, "alpha");
    writeFileSync(h.overridePath("alpha"), preBug6Override("alpha", 1));

    await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    expect(h.out.join("")).toMatch(/Restart at your convenience/);
  });

  it("does NOT emit the restart note when nothing changed", async () => {
    writeConfig(h, [{ name: "alpha", offset: 1 }]);
    ensureProfileDir(h, "alpha");
    writeFileSync(
      h.overridePath("alpha"),
      renderComposeOverride({ profile: "alpha", portOffset: 1 }),
    );

    await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    expect(h.out.join("")).not.toMatch(/Restart at your convenience/);
  });

  // ── AI_USERNAME build-arg backfill (vessel rebuild identity) ─────────
  //
  // Surfaced 2026-05-10 (Mirin r2 + Pax): operator-direct
  // `docker compose build vessel` against a per-profile override fell back
  // to the Dockerfile's ARG default (`vessel`) and the rebuilt image lost
  // the AI's home dir. profile fix now reads aiUsername from the profile's
  // session_config.json and bakes the build-arg into the override.

  it("reads aiUsername from session_config.json and emits the build-arg", async () => {
    writeConfig(h, [{ name: "alpha", offset: 5 }]);
    ensureProfileDir(h, "alpha");
    writeFileSync(h.overridePath("alpha"), preBug6Override("alpha", 5));
    writeFileSync(
      join(h.repoRoot, "workspace", "profiles", "alpha", "session_config.json"),
      JSON.stringify({
        externalLlmApiKey: "k",
        provider: "google",
        modelId: "gemini-flash-latest",
        aiName: "Mirin",
        aiUsername: "mirin",
        difficulty: "normal",
        createdAt: 1,
        sessionId: "session_1",
      }),
    );

    await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );

    const after = readFileSync(h.overridePath("alpha"), "utf-8");
    expect(after).toMatch(
      /vessel:[\s\S]*?build:\s*\n\s+args:\s*\n\s+AI_USERNAME: mirin/,
    );
  });

  it("skips the build-arg block when session_config.json is missing", async () => {
    // Profiles that were created via `arianna profile create <name>` without
    // any --provider/--model flags don't have session_config.json yet; the
    // TUI lobby writes it later. Backfill must not crash, and must not
    // emit a half-formed build block (which would resolve to AI_USERNAME=).
    writeConfig(h, [{ name: "alpha", offset: 5 }]);
    ensureProfileDir(h, "alpha");
    writeFileSync(h.overridePath("alpha"), preBug6Override("alpha", 5));
    // No session_config.json written.

    await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );

    const after = readFileSync(h.overridePath("alpha"), "utf-8");
    expect(after).not.toMatch(/build:/);
    expect(after).not.toMatch(/AI_USERNAME/);
    // ARIANNA_PROFILE backfill still happened — build-arg is additive.
    expect(after).toMatch(/ARIANNA_PROFILE: alpha/);
  });

  it("skips the build-arg block when session_config.json lacks aiUsername", async () => {
    writeConfig(h, [{ name: "alpha", offset: 5 }]);
    ensureProfileDir(h, "alpha");
    writeFileSync(h.overridePath("alpha"), preBug6Override("alpha", 5));
    writeFileSync(
      join(h.repoRoot, "workspace", "profiles", "alpha", "session_config.json"),
      JSON.stringify({ aiName: "Mirin" }), // no aiUsername field
    );

    await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    const after = readFileSync(h.overridePath("alpha"), "utf-8");
    expect(after).not.toMatch(/AI_USERNAME/);
  });

  it("tolerates malformed session_config.json (no crash, no build-arg)", async () => {
    writeConfig(h, [{ name: "alpha", offset: 5 }]);
    ensureProfileDir(h, "alpha");
    writeFileSync(h.overridePath("alpha"), preBug6Override("alpha", 5));
    writeFileSync(
      join(h.repoRoot, "workspace", "profiles", "alpha", "session_config.json"),
      "{ this is not json",
    );

    const code = await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    expect(code).toBe(0);
    const after = readFileSync(h.overridePath("alpha"), "utf-8");
    expect(after).not.toMatch(/AI_USERNAME/);
  });

  it("is idempotent when aiUsername is set (re-run produces byte-equal output)", async () => {
    writeConfig(h, [{ name: "alpha", offset: 5 }]);
    ensureProfileDir(h, "alpha");
    writeFileSync(
      join(h.repoRoot, "workspace", "profiles", "alpha", "session_config.json"),
      JSON.stringify({ aiUsername: "mirin" }),
    );
    writeFileSync(
      h.overridePath("alpha"),
      renderComposeOverride({
        profile: "alpha",
        portOffset: 5,
        aiUsername: "mirin",
      }),
    );
    const before = readFileSync(h.overridePath("alpha"), "utf-8");

    await runProfileFix(
      { dryRun: false },
      {
        write: h.write,
        homeDir: h.homeDir,
        repoRoot: h.repoRoot,
        ariannaHome: h.ariannaHome,
      },
    );
    expect(readFileSync(h.overridePath("alpha"), "utf-8")).toBe(before);
    expect(h.out.join("")).toMatch(/already current/);
  });
});
